name: Test run
run-name: Just testing the absolute basics of executing a net application and catching the output
on:
  workflow_dispatch:
jobs:
  execute-and-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"
      - name: Install dependencies
        run: dotnet restore src/Test.NetExecuteWorkflow/Test.NetExecuteWorkflow/Test.NetExecuteWorkflow.csproj
      - name: Build
        run: dotnet build --configuration Release --no-restore src/Test.NetExecuteWorkflow/Test.NetExecuteWorkflow/Test.NetExecuteWorkflow.csproj
      - name: Execute
        run: dotnet run --no-build --configuration Release --no-restore --project src/Test.NetExecuteWorkflow/Test.NetExecuteWorkflow/Test.NetExecuteWorkflow.csproj
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: /home/runner/work/Test.NetExecuteWorkflow/Test.NetExecuteWorkflow/out/
  upload-to-azure:
    needs: execute-and-generate
    runs-on: ubuntu-latest
    steps:  
        - name: Download artifact
          uses: actions/download-artifact@v3
          with:
            name: output
        - name: Upload to Azure
          uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
          with:
            azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
            action: "upload"
            app_location: "/"